name: Lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  Lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: SwiftFormat
        run: swiftformat --lint . --reporter github-actions-log
